<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119015023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exercise_id INT NOT NULL, set_rep_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_704B80A0E934951A ON exercise_set (exercise_id)');
        $this->addSql('CREATE INDEX IDX_704B80A0F0807C7B ON exercise_set (set_rep_id)');
        $this->addSql('CREATE TABLE set_rep (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, repetition INT NOT NULL, sets INT NOT NULL, rest_time INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, cpf VARCHAR(15) NOT NULL, phone VARCHAR(15) NOT NULL, birthday DATE NOT NULL, gender VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6493E3E11F0 ON "user" (cpf)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE workout_exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exercise_set_id INT NOT NULL, workout_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5744C04465B49873 ON workout_exercise_set (exercise_set_id)');
        $this->addSql('CREATE INDEX IDX_5744C044A6CCCFC9 ON workout_exercise_set (workout_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE exercise_set ADD CONSTRAINT FK_704B80A0E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_set ADD CONSTRAINT FK_704B80A0F0807C7B FOREIGN KEY (set_rep_id) REFERENCES set_rep (id)');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C04465B49873 FOREIGN KEY (exercise_set_id) REFERENCES exercise_set (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C044A6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_set DROP CONSTRAINT FK_704B80A0E934951A');
        $this->addSql('ALTER TABLE exercise_set DROP CONSTRAINT FK_704B80A0F0807C7B');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C04465B49873');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C044A6CCCFC9');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_set');
        $this->addSql('DROP TABLE set_rep');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise_set');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
