<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220220311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE execution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AEDAD51C5E237E06 ON exercise (name)');
        $this->addSql('CREATE TABLE exercise_execution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exercise_id INT NOT NULL, execution_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC77D1D0E934951A ON exercise_execution (exercise_id)');
        $this->addSql('CREATE INDEX IDX_AC77D1D057125544 ON exercise_execution (execution_id)');
        $this->addSql('CREATE UNIQUE INDEX exercise_execution_unique ON exercise_execution (exercise_id, execution_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, cpf VARCHAR(15) NOT NULL, phone VARCHAR(15) NOT NULL, birthday DATE NOT NULL, gender VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6493E3E11F0 ON "user" (cpf)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, trainee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_649FFB725E237E06 ON workout (name)');
        $this->addSql('CREATE INDEX IDX_649FFB7236C682D0 ON workout (trainee_id)');
        $this->addSql('CREATE TABLE workout_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rest_time INT DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, position INT DEFAULT NULL, exercise_execution_id INT DEFAULT NULL, workout_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76AB38AABD8AE06D ON workout_exercise (exercise_execution_id)');
        $this->addSql('CREATE INDEX IDX_76AB38AAA6CCCFC9 ON workout_exercise (workout_id)');
        $this->addSql('CREATE UNIQUE INDEX workout_exercise_unique ON workout_exercise (workout_id, exercise_execution_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE exercise_execution ADD CONSTRAINT FK_AC77D1D0E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_execution ADD CONSTRAINT FK_AC77D1D057125544 FOREIGN KEY (execution_id) REFERENCES execution (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB7236C682D0 FOREIGN KEY (trainee_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AABD8AE06D FOREIGN KEY (exercise_execution_id) REFERENCES exercise_execution (id)');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_execution DROP CONSTRAINT FK_AC77D1D0E934951A');
        $this->addSql('ALTER TABLE exercise_execution DROP CONSTRAINT FK_AC77D1D057125544');
        $this->addSql('ALTER TABLE workout DROP CONSTRAINT FK_649FFB7236C682D0');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AABD8AE06D');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAA6CCCFC9');
        $this->addSql('DROP TABLE execution');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_execution');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
