<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115143112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(255) DEFAULT NULL, difficulty INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) DEFAULT NULL, exercise_id INT NOT NULL, set_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_704B80A0E934951A ON exercise_set (exercise_id)');
        $this->addSql('CREATE INDEX IDX_704B80A010FB0D18 ON exercise_set (set_id)');
        $this->addSql('CREATE TABLE set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, repetition INT NOT NULL, load INT DEFAULT NULL, rest_time INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, date DATE NOT NULL, duration INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE workout_exercise_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, exercise_set_id INT NOT NULL, workout_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5744C04465B49873 ON workout_exercise_set (exercise_set_id)');
        $this->addSql('CREATE INDEX IDX_5744C044A6CCCFC9 ON workout_exercise_set (workout_id)');
        $this->addSql('ALTER TABLE exercise_set ADD CONSTRAINT FK_704B80A0E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_set ADD CONSTRAINT FK_704B80A010FB0D18 FOREIGN KEY (set_id) REFERENCES set (id)');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C04465B49873 FOREIGN KEY (exercise_set_id) REFERENCES exercise_set (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workout_exercise_set ADD CONSTRAINT FK_5744C044A6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_set DROP CONSTRAINT FK_704B80A0E934951A');
        $this->addSql('ALTER TABLE exercise_set DROP CONSTRAINT FK_704B80A010FB0D18');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C04465B49873');
        $this->addSql('ALTER TABLE workout_exercise_set DROP CONSTRAINT FK_5744C044A6CCCFC9');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_set');
        $this->addSql('DROP TABLE set');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise_set');
    }
}
